build:
  maxIssues: 0

config:
  validation: true
  warningsAsErrors: false

naming:
  FunctionNaming:
    active: true
    functionPattern: '[a-zA-Z][a-zA-Z0-9]*'
    ignoreAnnotated:
      - 'Composable'
      - 'Preview'

complexity:
  LongParameterList:
    active: true
    functionThreshold: 8
    constructorThreshold: 8
    ignoreAnnotated:
      - 'Composable'
      - 'Inject'
      - 'AssistedInject'
  TooManyFunctions:
    active: true
    thresholdInFiles: 20
    thresholdInClasses: 15
    thresholdInInterfaces: 10
    thresholdInObjects: 15
    thresholdInEnums: 10

style:
  MagicNumber:
    active: true
    ignoreNumbers:
      - '-1'
      - '0'
      - '1'
      - '2'
    ignoreHashCodeFunction: true
    ignorePropertyDeclaration: true
    ignoreConstantDeclaration: true
    ignoreCompanionObjectPropertyDeclaration: true
    ignoreNamedArgument: true
    ignoreEnums: true
    ignoreAnnotated:
      - 'Preview'
      - 'Composable'
  UnusedPrivateMember:
    active: true
    allowedNames: '(_|ignored|expected|serialVersionUID)'
